# Generated by Django 5.2 on 2025-05-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_categories'),
        ('events', '0003_event_created_at_event_expected_attendance_and_more'),
    ]

    operations = [
    ]
