# Generated by Django 5.2 on 2025-06-09 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_merge_20250511_2123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='provider',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='provider',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='api_source',
            field=models.CharField(choices=[('YELP', 'Yelp'), ('GOOGLE', 'Google'), ('RAPIDAPI', 'RapidAPI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='EventProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('price_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='events.event')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.provider')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'provider')},
            },
        ),
    ]
